### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Vaibhavdixit02** [Vaibhavdixit02/SymbolicAnalysis.jl#35]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by Vaibhavdixit02** [comment]
@JuliaRegistrator register()

**Comment by oscardssmith** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
