### ISSUE TITLE
Decide how to handle functions with different behaviour in different domains

### ISSUE THREAD

**Issue by Vaibhavdixit02** [Vaibhavdixit02/SymbolicAnalysis.jl#6]

**Comment by shashi** [comment]
What does this mean?

**Comment by Vaibhavdixit02** [comment]
The properties of a function could be different depending on the domain, right now it just overwrites the entry if there are two `add_dcprule` calls

**Comment by Vaibhavdixit02** [comment]
Fixed in https://github.com/Vaibhavdixit02/SymbolicAnalysis.jl/pull/14/commits/b4e3d5317aa4202b0b7e14dc2daf755de5d5d0bd
